site:
  title: Documentation
  url: https://eclectic-sawine-19fcf1.netlify.app
  start_page: clc::overview.adoc
  robots: disallow
#  keys:
#    docsearch_id: 'QK2EAH8GB0'
#    docsearch_api: 'ef7bd9485eafbd75d6e8425949eda1f5'
#    docsearch_index: 'prod_hazelcast_docs'
#content:
#  sources:
#  - url: .
#    branches: HEAD
#    start_path: docs
#ui:
#  bundle:
#    url: https://github.com/hazelcast/hazelcast-docs-ui/releases/latest/download/ui-bundle.zip #../hazelcast-docs-ui/build/ui-bundle.zip
#    snapshot: true
asciidoc:
  extensions:
    - ./node_modules/hazelcast-docs-tools/antora-macro/tabs-block.js
    - asciidoctor-kroki
