= Advanced Scripting Guide

:description: This guide will show you how to write Advanced Scripts for CLC.

{description}

== Introduction

Hazelcast CLC provides scriptability using a Python-like language called Starlark.

The Advanced Scripts should have the `.star` extension.
Throughout this guide, the "advanced script" is meant when the "script" is mentioned.

The code in a script is organized in two parts: the top-level and optional functions.
The `main` function is executed after all statements in the top-level is executed, so the script below prints `Top-Level A`, `Top-Level C`, `Main B` lines.

[source,python]
----
print("Top-Level A")

def main():
    print("Main B")

print("Top-Level C")
----

There are a few constraints about top-level code:

1. Variables defined in the top-level become global immutable variables, they cannot be reassigned.
2. Loops are not allowed.
3. Conditional statements are not allowed.

These constraints do not exist in code written in functions.
`main` function is a convenient place to write your code.

== Your First Script

Having these points in mind, let's write our first script.
This script is going to print the total number of entries across all maps.
Open your favorite code editor and optionally turn on the Starlark mode if available or the Python 3 mode.
Save the following code as `hello.star`:

[source,python]
----
def main():
    total_entries = 0
    for map_name in object_list("map"):
        total_entries += map_size(name=map_name)
    print("OK There are {} entries.".format(total_entries))
----

This code iterates on the Map names in the cluster, retrieves the entry count for the corresponding Maps and sums them.
Finally it displays the total number of entries.

Before running the script, let's make sure we have a few Maps in the cluster.
Run the following commands in a terminal window to create three Maps with some data in them:

[source,bash]
----
clc demo map-setmany -n map1 10
clc demo map-setmany -n map2 20
clc demo map-setmany -n map3 30
----

You are ready to run the script:

[source,bash]
----
clc script hello.star
----

You should get an output similar to:

----
OK There are 60 entries.
----

== Data Types

Advanced scripts support various data types.
Some of the data types are common to all Starlark scripts.
And others are CLC-specific.

Here is a summary of the Starlark provided types:

[source,python]
----
just_none = None
a_boolean = True
an_integer = 38
a_float = 42.24
a_string = "Hazelcast"
a_list = [1, "two", 3.33, False]
a_tuple = (1, "two")
a_dictionary = {1: "one", "two": 2}
a_user_function = lambda: "some value"
a_builtin_function = len
----

You can check out the documentation for those data types at link:https://github.com/google/starlark-go/blob/master/doc/spec.md#data-types[Starlark Data Types].

=== Data Value [[data_value]]

CLC introduces the `data` type, which contains the data object returned from distributed data structure (DDS) calls, such as `map_get`.
The data object is a serialized object which can be directly passed to another DDS call.
It's crucial to keep these object in their serialized form.
Because they may be serialized in a way which cannot be deserialized by CLC, such as Java Serializable objects.
By keeping the objects in their original serialized form, CLC is able to use those objects as keys and values in an opaque way.

Currently, the only way to create data values is reading one using a DDS call.
Here's some code that does that, save it as `data_value.star`

[source,python]
----
map_set("some-key", "some-value")
obj = map_get("some-key")
print(type(obj))
----

Running it:

[source,bash]
----
clc script data_value.star
----

Outputs:
----
data
----

Once a data object is retrieved, you can check its type or deserialize it if its one of the supported data types.
Here are the methods and functions which can be used with a data object:

* `X.type`: Returns the serialization identifier.
* `data_type(X)`: Returns the name of the serializer.
* `data_value(X)`: Deserializes the value. Note that CLC cannot deserialize all values. An error will be raised in case the value was not deserialized.

The script below summarizes the methods above.
Save it as `data_value2.star`:

[source,python]
----
map_set("some-key", "some-value")
obj = map_get("some-key")
print("String value of the data object     :", obj)
print("Numeric type of the enclosed object :", obj.type)
print("String value of the enclosed object :", data_type(obj))
print("The deserialized object             :", data_value(obj))
----

Running it:

[source,bash]
----
clc script data_value2.star
----

Outputs:
----
String value of the data object     : data(STRING)
Numeric type of the enclosed object : -11
String value of the enclosed object : STRING
The deserialzed object              : some-value
----

== User Defined Functions

You can define regular functions using the `def` keyword and anonymous functions using the `lambda` keyword.

Here's an example function which takes the square of the given number.
Save it as `fun.star`:

[source,python]
----
def sqr(a):
    return a * a

print(sqr(5))
----

Running the script outputs:
----
25
----

Check out more about functions in the link:https://github.com/google/starlark-go/blob/master/doc/spec.md#function-definitions[Starlark functions] documentation.

Anonymous functions are useful to define trivial, inline functions.
In the example below a list of numbers are iterated and a new list is created by calling a function with each item.
Save the script as `anonymous.star`:

[source,python]
----
def main():
    my_list = [1, 2, 3, 5, 10]
    funs = [
        ("identity", lambda x: x),
        ("squared", lambda x: x * x),
        ("10 more", lambda x: x + 10),
    ]
    for label, f in funs:
        new_list = [f(x) for x in my_list]
        print(label, new_list)
----

Running the script outputs:
----
identity [1, 2, 3, 5, 10]
squared [1, 4, 9, 25, 100]
10 more [11, 12, 13, 15, 20]
----

link:https://github.com/google/starlark-go/blob/master/doc/spec.md#lambda-expressions[Starlarl lambda expressions] documentation contains more information about anonymous functions.

== Builtin Functions

=== Map Functions

You can use several Map functions in your advanced scripts.
See the link:clc-script.adoc[script] command documentation for the list of the functions available to advance scripts.
In this section, you are going to use some of those functions.

The `map_set` function sets a value for a key in a Map.
The key may be any Starlark value or it can be encoded data.
And the `map_get` function returns the encoded data for the given key.
Save the following script as `map1.star`.
[source,python]
----
def main():
    map_name = "num-map"
    for i in range(3):
        map_set(i, "value-{}".format(i), name=map_name)
    print("Map size:", map_size(name=map_name))
    for i in range(3):
        value = map_get(i, name=map_name)
        decoded_value = data_value(value)
        print("Value:", decoded_value)
----
Running this script outputs:
----
Map size: 3
Data for 0 is data(STRING) and its value is value-0
Data for 1 is data(STRING) and its value is value-1
Data for 2 is data(STRING) and its value is value-2
----

Note the `value = map_get(i, name=map_name)` line.
`map_get` command returns the encoded data, not the actual value you passed to `map_set`.
That's different from official Hazelcast client libraries, which decode the data and return the decoded the value.
You have already read the explanation for that behavior in the <<data_value>> section.

`map_key_set` returns the list of keys for a member. Let's now use that function to make the example above a bit more robust by getting the keys from the cluster instead of manually specifying them.
Save the following script as `map2.star`:
[source, python]
-----
def main():
    map_name = "num-map"
    for i in range(3):
        map_set(i, "value-{}".format(i), name=map_name)
    print("Map size:", map_size(name=map_name))
    for key in map_key_set(name=map_name):
        value = map_get(key, name=map_name)
        decoded_value = data_value(value)
        print("Value:", decoded_value)
-----

You can also use the `map_entry_set` function to get a list of `(key, value)` pairs of a map.
Let's modify the script above to use that function.
Save the following script as `map3.star`:
[source, python]
-----
def main():
    map_name = "num-map"
    for i in range(3):
        map_set(i, "value-{}".format(i), name=map_name)
    print("Map size:", map_size(name=map_name))
    for key, value in map_entry_set(name=map_name):
        decoded_value = data_value(value)
        print("Value:", decoded_value)
-----

=== Utilities

==== argv

The `argv` function returns the arguments passed to the script in a list.
The first item (index 0) is the script's name.

Save the following script as `args.star`:

[source,python]
----
def main():
    args = argv()
    print("Script     :", args[0])
    for i, arg in enumerate(args[1:]):
        print("Argument", i + 1, ":", arg)
----

1. Let's run it with no arguments:
+
[source,bash]
----
clc script args.star
----
+
Output:
+
----
Script     : args.star
----
+
2. Let's run it with 3 arguments:
+
[source,bash]
----
clc script args.star -- foo bar quux
----
+
Output:
+
----
Script     : args.star
Argument 1 : foo
Argument 2 : bar
Argument 3 : quux
----
+
3. Now let's try passing a flag to our script.
Remember that flags has the dash `-` as a prefix:
+
[source,bash]
----
clc script args.star -- foo --my-flag
----
+
Output:
+
----
Script     : args.star
Argument 1 : foo
Argument 2 : --my-flag
----

You may be wondering why `--` after the script path is necessary.
The reason for that is, the flags for the `script` command may appear anywhere in the command line, even at the end.
You must use `--` before any flag that must be passed to the script itself to help the argument parser.
If there are no flags passed to script, you may leave out `--`, but using it always helps with having less errors.

==== env

You can access the environment variables using the `env` command.
When run without arguments, it returns the list of (name, value) pairs.
Save the following script as `env1.star`.

[source,python]
----
def main():
    for name, value in env():
        print(name, "=", value)
----

Running the script outputs all environment variables.
----
DESKTOP_SESSION = plasma
DISPLAY = :0
EDITOR = /usr/bin/vim
GDK_BACKEND = x11
----

You can also get the value of a single environment variable, by passing its name to `env`.
Here's an example:
[source, python]
----
user_home = env("HOME")
print("My home directory:", user_home)
----

==== now

`now()` function returns the current local time in nanoseconds.

You can easily convert the time to other units using the predefined time units, such as `millisecond`, `second` and `day`.
Check out the link:clc-script.adoc[script] command reference for others.
Here's a small example that measures the time an `object_list` operation takes and prints the result in various time units.

[python,source]
----
time = now()
print(time)
----

You can easily convert the time from nanoseconds to other time units using the provided builtin values.
See the link:clc-script.adoc[script] command documentation for all time units.
Here's an example that shows how to convert nanoseconds to other time units.
Save the following script as `time.star`:

[source,python]
----
tic = now()
object_list()
toc = now()
took = toc - tic

print("The operation took:")
print("  ", took//nanosecond, "nanoseconds")
print("  ", took//microsecond, "microseconds")
print("  ", took//millisecond, "milliseconds")
print("  ", took//second, "seconds")
----

Running it outputs:
----
The operation took:
   4152911 nanoseconds
   4152 microseconds
   4 milliseconds
   0 seconds
----

==== sleep

It may sometimes be necessary to wait a bit before doing other work.
`sleep` command waits for the given time in nanoseconds.
It's very easy to use other time units, such as milliseconds and seconds.
See the link:clc-script.adoc[script] command documentation for all time units.
Here's a script that just waits for 2 seconds.

[source,python]
----
print("Falling asleep...")
sleep(2*second)
print("Woke up")
----



=== Logging

CLC provides several logging functions, which log messages using CLC's logging mechanism.

* `log_error(STRING_OR_ERROR)`: Logs a message or an error with the ERROR level.
* `log_warn(STRING)`: Logs a message with the WARN level.
* `log_info(STRING)`: Logs a message with the INFO level.
* `log_debug(STRING)`: Logs a message with the DEBUG level.

If the logging level set with `--log.level` is above the message's log level, then it is not written to the log.
For example, if `--log.level error` specified then only `log_error` functions log messages.

The `--log.path PATH` flag works as expected and can be used to redirect the log messages to the given file or to STDERR (usually the terminal) if `stderr` is used.

Here is a sample script to try the interplay of the log messages and logging levels.
Save it as `logging.star`.

[source,python]
----
log_error("This is an error log")
log_warn("This is is a warn log")
log_info("This is an info log")
log_debug("This is a debug log")
----

First, run it as follows.
Note that we set `--log.path stderr` to see the logs on the screen.
Otherwise they would written in the default log file.

[source, bash]
----
clc script --log.path stderr --log.level error logging.star
----

Since only log messages above ERROR are to be displayed, you should get output similar to the following:

----
2023-11-01T11:24:18+03:00  ERROR  [logging.star:2:10] This is an error log
----

Let's try once more with a different log level.
This time with DEBUG:

[source, bash]
----
clc script --log.path stderr --log.level debug logging.star
----

This time all log messages should be displayed and you should get output similar to the following:

----
2023-11-01T21:30:13+03:00  ERROR  [logging.star:2:10] This is an error log
2023-11-01T21:30:13+03:00   WARN  [logging.star:3:9] This is is a warn log
2023-11-01T21:30:13+03:00   INFO  [logging.star:4:9] This is an info log
2023-11-01T21:30:13+03:00  DEBUG  [logging.star:5:10] This is a debug log
----

=== Debugging

Debug functions start with double underscores (`__`).
They run only when the debug mode is activated by passing `--debug` flag to the `script` command.
If the debug mode is not active, they are no-ops.

==== __trace

You can use the `__trace` function to print the script name, line and column of the location whenever it is run.
You can also customize the trace message by passing a string to `__trace`.
Save the following script as `trace.star`.

[source,python]
----
def fun1():
    __trace()
    print("Fun 1")

__trace("Start-up")
fun1()
----

Running the script normally:
----
clc script trace.star
----
Outputs:
----
Fun 1
----
That's because the `__trace` calls are removed.
Try again with the `--debug` flag:
----
clc script --debug trace.star
----
Outputs:
----
>> Start-up: trace.star:5:8
>> TRACE: trace.star:2:12
Fun 1
----

== Output

=== Type of CLC Output

CLC supports two kinds of output: structured and "unnecessary".
Let's talk about them over an example.

`clc demo generate-data` command creates data in a Map or to the terminal.
Let's run it and analyze its output:

[source,bash]
----
clc demo generate-data wikipedia-event-stream --preview --yes --max-values 1
----

Running that command generates output similar to the following:
----
Following mapping will be created when run without preview:

CREATE OR REPLACE MAPPING "<map-name>"
(
    -- ...SNIP...
);

-------------------------------------------------------------------------------------------------------------------------------------------
 ID                               | Timestamp                        | User                             | Comment
-------------------------------------------------------------------------------------------------------------------------------------------
 aa1d8f0b-2218-4ac7-aaec-727eb109 | 2023-11-03T10:07:39Z             | Dcirovicbot                      | /* wbeditentity-update-languages
 6e25                             |                                  |                                  | -short:0||bs */
-------------------------------------------------------------------------------------------------------------------------------------------
----

In the output, the table is the structured output and the rest is "unnecessary" output.
Of course the information in the "unnecessary" output is not really unnecessary, but it is not as important as the structured output and you can get rid of that using the `-q` flag:

[source,bash]
----
clc demo generate-data wikipedia-event-stream --preview --yes --max-values 1 -q
----

Now the output contains only the structured output:
----
-------------------------------------------------------------------------------------------------------------------------------------------
 ID                               | Timestamp                        | User                             | Comment
-------------------------------------------------------------------------------------------------------------------------------------------
 aa1d8f0b-2218-4ac7-aaec-727eb109 | 2023-11-03T10:07:39Z             | Dcirovicbot                      | /* wbeditentity-update-languages
 6e25                             |                                  |                                  | -short:0||bs */
-------------------------------------------------------------------------------------------------------------------------------------------
----

You can easily change the format of the structured output by using the `-f` flag, such as JSON:

[source,bash]
----
clc demo generate-data wikipedia-event-stream --preview --yes --max-values 1 -q -f json
----

Outputs (formatted for better display):
----
{
  "Comment": "* {{Bases géographiques}}",
  "ID": "bb142006-97e0-470f-8fd1-cd4dce344fe0",
  "Timestamp": "2023-11-03T10:45:06Z",
  "User": "Padawane"
}
----

=== Script Output

Just like CLC commands, advanced scripts can produce both structured and unnecessary output.
The `print` function produces unnecessary output, which can be suppressed with the `--quiet` (shortcut `-q`) flag, and the `output` command produces structured output. The structured output is written out as a table, but you can change it to other formats using the `--format` (shortcut `-f`) flag.

Here's an example to demonstrate that.
Save the script as `output1.star`:
[source,python]
----
def main():
    fruits = ["apple", "grapes", "pear"]
    print("There are {} fruits.".format(len(fruits)))
    print("Unnecessary output lines will dissapear when you use -q\n")

    for i, fruit in enumerate(fruits):
        output(Index=i, Fruit=fruit)
----

Let's first run it normally:
[source,bash]
----
clc script output1.star
----

Outputs:
----
There are 3 fruits.
Unnecessary output lines will dissapear when you use -q

----------------
 Index | Fruit
----------------
     0 | apple
     1 | grapes
     2 | pear
----------------
    OK Returned 3 row(s).
----

Let's now use the `-q` flag to suppress unnecessary output:
[source,bash]
----
clc script output1.star -q
----

Outputs:
----
----------------
 Index | Fruit
----------------
     0 | apple
     1 | grapes
     2 | pear
----------------
----

As expected, unnecessary output was not produced.
Using a different output format also works:
[source,bash]
----
clc script output1.star -q -f csv
----

Outputs:
----
Index,Fruit
0,apple
1,grapes
2,pear
----

Separating unnecessary and structured output makes it much easier to extracts the result using a pipe.
This example uses the link:https://jqlang.github.io/jq/[jq] utility:
:
[source,bash]
----
clc script output1.star -q -f json | jq '.Fruit'
----
Outputs:
----
"apple"
"grapes"
"pear"
----


Passing keyword arguments to `output` for column label and value may sometimes be limiting.
Since only valid Starlark identifiers can be used as the column label.
For example, running the following script will return an error:
[source,python]
----
def main():
    output(1=2)
----
Because of that, CLC also supports passing a dictionary to the `output` function.
In that case, the dictionary must be passed as a positional argument and it must be the only argument to `output`.
You can rewrite the following as follows and it will run just fine:
[source,python]
----
def main():
    output({1: 2})
----

The output function handles rows with missing values just fine.
Here's a script that demonstrate that.
Save it as `output2.star`:
[source,python]
----
def main():
    for i in range(3):
        output({i: "OK"})
----
Running it outputs the following:
----
--------------
 0  | 1  | 2
--------------
 OK | -  | -
 -  | OK | -
 -  | -  | OK
--------------
----
Different output formats handle missing values differently.
JSON printer just skips the missing values:
[source,bash]
----
clc script output2.star -f json
----
Outputs:
----
{"0":"OK"}
{"1":"OK"}
{"2":"OK"}
----

== Error Handling

Whenever an error occurs, CLC stops the script and prints an error message.
This is usually the safest way to handle the error.
But there are times when you would like to try something which can result in an error and handle it without giving back the control.

The `script` command supports `the --ignore-errors` flag that suppresses errors while running the script.
You can use the `last_error()` function to get the raised error and act on it.

Let's demonstrate that with an example using the `data_value` function.
Passing a string to `data_value` ends with an error, but we are going to cover "why?" in another section.
Save the following sctipt as `error.star`:

[source,python]
----
def main():
    v = data_value("foo")
    print(v)
----

And run it as:

[source,bash]
----
clc script error.star
----

You should get an error:
----
ERROR Error.star:2:19: argument 1 is expected to be 'serialization.Data', got 'string'
----

This time, run the script with the `--ignore-errors` flag:

[source,bash]
----
clc script --ignore-errors error.star
----

You should get the following output:
----
None
----

The error in the `data_value` line is ignored and `v` is set to `None`.

Let's now try to use the `last_error` function and act on errors.
Save the following script as `error2.star`:

[source,python]
----
def main():
    v = data_value("foo")
    if last_error():
        v = "OK Caught the error."
    print(v)
----

Run the script with the `--ignore-errors` flag:
[source,bash]
----
clc script --ignore-errors error2.star
----

This time the output is:

----
OK Caught the error.
----

