= \alias

Alias commands enable you to add and list user defined shortcuts.

In order to persist the aliases you need to add `\alias add` statements in the `$CLC_HOME/shell.clc` script. `shell.clc` script is sourced when CLC starts in the interactive mode.

NOTE: Alias commands can only be used in the interactive and scripting modes.

Aliases can be used with the `@` prefix. For example, an alias named `my-alias` can be used as `@my-alias`.

Usage:

[source,bash]
----
\alias [command]
----

== Commands

* <<alias-add, \alias add>>
* <<alias-remove, \alias remove>>
* <<alias-list, \alias list>>

== \alias add

Add an alias with the given name and command.

Usage:

[source,bash]
----
-- for command
\alias add {ALIAS-NAME} -- {\\COMMAND}

-- for SQL
\alias add {ALIAS-NAME} -- {SQL}
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`name`
|Required
|Name of the alias.
|

|`command`
|Required
|
|

|===

Examples:

- Adds an alias to list maps in the cluster:
[source,bash]
----
\alias add list-maps -- \\object list map
----

- Adds an alias to query SQL:
[source,bash]
----
\alias add first-five-desserts -- select name from desserts order by name limit 5;
----

== \alias remove

Remove an alias with the given name.

Usage:

[source,bash]
----
\alias remove [name]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`name`
|Required
|Name of the alias.
|

|===

Example:

[source,bash]
----
\alias remove my-alias
----

== \alias list

List existing aliases.

Usage:

[source,bash]
----
\alias list
----

Example:

[source,bash]
----
\alias list
----

=== Alias Usage

Aliases can be used in interactive and scripting modes with `@` prefix. Let's assume an alias named `my-alias` already created. it can be used as `@my-alias`.