= User Defined Aliases

Alias commands enable you to add and list user defined shortcuts.

Alias commands can only be used in the interactive and scripting modes.

In order to persist the aliases you need to define the `\alias add` statements in the `$CLC_HOME/shell.clc` script which is automatically run when CLC starts in the interactive mode.

Usage:

[source,bash]
----
clc alias [command]
----

== Commands

* <<clc-alias-add, clc alias add>>
* <<clc-alias-remove, clc alias remove>>
* <<clc-alias-list, clc alias list>>

== clc alias add

Add an alias with the given name and command.

Usage:

[source,bash]
----
-- for command
\alias add {ALIAS-NAME} -- {\\COMMAND}

-- for SQL
\alias add {ALIAS-NAME} -- {SQL}
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`name`
|Required
|Name of the alias.
|

|`command`
|Required
|
|

|
|===

Examples:

- Adds an alias to list maps in the cluster:
[source,bash]
----
clc alias add list-maps -- \\object list map
----

- Adds an alias to query SQL:
[source,bash]
----
clc alias add first-five-desserts -- select name from desserts order by name limit 5;
----

To run an alias, prefix its name with an `@`:

Using the above as examples, `@list-maps` and `@first-five-desserts` will run the respective aliases.

NOTE: In order to persist the aliases you need to define the `\alias add` statements in the `$CLC_HOME/shell.clc` script which is automatically run when CLC starts in the interactive mode.

== clc alias remove

Remove an alias with the given name.

Usage:

[source,bash]
----
clc alias remove [name]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`name`
|Required
|Name of the alias.
|

|
|===

Example:

[source,bash]
----
clc alias remove my-alias
----

NOTE: `alias remove` removes the alias from the current session only. To remove the alias permanently, remove the `\alias add` statement from the `$CLC_HOME/shell.clc` script.

== clc alias list

List existing aliases.

Usage:

[source,bash]
----
clc alias list
----

Example:

[source,bash]
----
clc alias list
----

=== Alias Usage

Aliases can be used in interactive and scripting modes with `@` prefix. Let's assume an alias named `my-alias` already created, it can be used as `@my-alias`.