= clc config

Configuration operations.

Usage:

[source,bash]
----
clc config [command] [flags]
----

== Commands

* <<clc-config-add, clc config add>>
* <<clc-config-import-cloud, clc config import-cloud>>
* <<clc-config-import-java, clc config import-java>>
* <<clc-config-list, clc config list>>

== clc config add

Adds a named configuration with the given values. Specify the configurations as `KEY=VALUE` pairs.

It overwrites the previous configuration if it exists.

Usage:

[source,bash]
----
clc config add [target] [source] [flags] [key=value...]
----

You can pass key=value pairs to add configuration items.

.Configuration keys
[%collapsible]
====
include::partial$configuration-items.adoc[]
====

.Global parameters
[%collapsible]
====
include::partial$global-parameters.adoc[]
====

Example output:

[source,bash]
----
clc config add dev cluster.name=dev cluster.address=localhost:5701
----

== clc config import-cloud

Imports configuration from a {hazelcast-cloud} CLI sample.

To get the URL for {hazelcast-cloud}, follow the steps below:

1.  Open the {hazelcast-cloud} console, and select *Dashboard* -> *Connect Client* -> *CLI*
2. Copy the URL from the second step of the on-screen instructions, and pass it as the second parameter.
Ensure that the URL is enclosed in quotation marks, then run:
+
[source,bash]
----
clc config import-cloud my-config "URL copied from console"
----

.Global parameters
[%collapsible]
====
include::partial$global-parameters.adoc[]
====

== clc config import-java

This command imports a subset of Hazelcast Java client configuration and saves it as CLC configuration.

The Java keystore and truststore, referred in the XML configuration, are converted to PEM files.

Usage:

[source,bash]
----
clc config import-java [target] [source] [flags] [key=value...]
----

You can pass `key=value` pairs to override configuration options.

.Configuration keys
[%collapsible]
====
include::partial$configuration-items.adoc[]
====

Parameters:

[cols="1m,1m,2a,1m"]
|===
|Parameter|Required|Description|Default

|`target`
|Required
|Name or path to the configuration to create
|

| `source`
|Required
|Path to the Java client XML configuration
|

|`--ca-alias`
|Optional
|Alias of the CA certificate in the Java truststore
|

|`--cert-alias`
|Optional
|Alias of the certificate in the Java truststore
|

|`--key-alias`
|Optional
|Alias of the key in the Java keystore
|

|===

=== Limitations

Only PKCS12 keystores/truststores are supported.

The following are not supported:

* JKS keystores/trustores
* <import> and <config-replacers> tags
* Variables in .xml configuration

.Global parameters
[%collapsible]
====
include::partial$global-parameters.adoc[]
====


== clc config list

Lists the known configurations.

A known configuration is a directory at `$CLC_HOME/configs` that contains config.yaml.
Directory names which start with dot (`.`) or underscore (`_`) are ignored.

Usage:

[source,bash]
----
clc config list [flags]
----

Example output:

[source,bash]
----
clc config list
default
production
----
