= clc cloud
:page-aliases: clc-viridian.adoc

This command group provides commands for doing various operations on Hazelcast {hazelcast-cloud}, such as creating and managing clusters.

All commands except `cloud login` require the generation of a token using an API key and secret, which you can retrieve from the {hazelcast-cloud} console. Running `cloud login` prompts you for this information, and creates and saves the token.

Usage:

[source,bash]
----
clc cloud [command] [options]
----

== Commands

* <<clc-cloud-login, clc cloud login>>
* <<clc-cloud-create-cluster, clc cloud create-cluster>>
* <<clc-cloud-get-cluster, clc cloud get-cluster>>
* <<clc-cloud-list-clusters, clc cloud list-clusters>>
* <<clc-cloud-stop-cluster, clc cloud stop-cluster>>
* <<clc-cloud-resume-cluster, clc cloud resume-cluster>>
* <<clc-cloud-delete-cluster, clc cloud delete-cluster>>
* <<clc-cloud-download-logs, clc cloud download-logs>>
* <<clc-cloud-stream-logs, clc cloud stream-logs>>
* <<clc-cloud-import-config, clc cloud import-config>>
* <<clc-cloud-list-custom-classes, clc cloud list-custom-classes>>
* <<clc-cloud-upload-custom-class, clc cloud upload-custom-class>>
* <<clc-cloud-download-custom-class, clc cloud download-custom-class>>
* <<clc-cloud-delete-custom-class, clc cloud delete-custom-class>>

== clc cloud login

Logs in to {hazelcast-cloud} using the given API key and API secret and retrieves a token.
The token is cached to be used by other commands.
If not specified, the key and the secret will be asked in a prompt.

Alternatively, you can use the following environment variables:

* `CLC_CLOUD_API_KEY`
* `CLC_CLOUD_API_SECRET`

Usage:

[source,bash]
----
clc cloud login [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_CLOUD_API_KEY` environment variable. If not given, an input prompt is shown.
|

|`--api-secret`
|Optional
|Sets the API secret. Overrides the `CLC_CLOUD_API_SECRET` environment variable. If not given, an input prompt is shown.
|

|===

== clc cloud create-cluster

Creates a {hazelcast-cloud} cluster.

Make sure you authenticate to the {hazelcast-cloud} API using `cloud login` before running this command.

Usage:

[source,bash]
----
clc cloud create-cluster [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_CLOUD_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|

|`--name`
|Optional
|Sets the name of the created cluster. If not given, an auto-generated name will be used.
|

|`--development`
|Optional
|Creates a development cluster.
|

|`--prerelease`
|Optional
|Creates the cluster with a prerelease image.
|

|===

== clc cloud get-cluster

Gets the information about the given {hazelcast-cloud} cluster.

Make sure you authenticate to the {hazelcast-cloud} API using `cloud login` before running this command.

Usage:

[source,bash]
----
clc cloud get-cluster [cluster-ID/name] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_CLOUD_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|

|===

== clc cloud list-clusters

Lists all {hazelcast-cloud} clusters for the logged in API key.

Make sure you authenticate to the {hazelcast-cloud} API using `cloud login` before running this command.

Usage:

[source,bash]
----
clc cloud list-clusters [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_CLOUD_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|

|===

== clc cloud stop-cluster

Stops the given {hazelcast-cloud} cluster.

Make sure you authenticate to the {hazelcast-cloud} API using `cloud login` before running this command.

Usage:

[source,bash]
----
clc cloud stop-cluster [cluster-ID/name] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_CLOUD_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|

|`--wait`
|Optional
|Waits for the cluster to be stopped.
|`false`

|===

== clc cloud resume-cluster

Resumes the given {hazelcast-cloud} cluster.

Make sure you authenticate to the {hazelcast-cloud} API using `cloud login` before running this command.

Usage:

[source,bash]
----
clc cloud resume-cluster [cluster-ID/name] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_CLOUD_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|

|`--wait`
|Optional
|Waits for the cluster to be resumed.
|`false`

|===

== clc cloud delete-cluster

Deletes the given {hazelcast-cloud} cluster. All data in the cluster is deleted irreversibly.

Make sure you authenticate to the {hazelcast-cloud} API using `cloud login` before running this command.

Usage:

[source,bash]
----
clc cloud delete-cluster [cluster-ID/name] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_CLOUD_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|

|`--yes`
|Optional
|Skips confirming the delete operation.
|

|`--wait`
|Optional
|Waits for the cluster to be deleted.
|`false`

|===

== clc cloud download-logs

Downloads the logs of the given {hazelcast-cloud} cluster.

Make sure you authenticate to the {hazelcast-cloud} API using `cloud login` before running this command.

Usage:

[source,bash]
----
clc cloud download-logs [cluster-ID/name] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_CLOUD_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|

|`--output-dir` `-o`
|Optional
|Output directory for the log files, if not given current directory is used.
|

|===

== clc cloud stream-logs

Outputs the logs of the given {hazelcast-cloud} cluster as a stream.

Make sure you authenticate to the {hazelcast-cloud} API using `cloud login` before running this command.

The log format may be one of:

* minimal: Only the log message
* basic: Time, level and the log message
* detailed: Time, level, thread, logger and the log message
* free form template, see: https://pkg.go.dev/text/template for the format.
You can use the following placeholders: `msg`, `level`, `time`, `thread` and `logger`.
Usage:

[source,bash]
----
clc cloud stream-logs [cluster-ID/name] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_CLOUD_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|

|`--log-format`
|Optional
|Format of log lines. Either a predefined or free form format.
|`basic`

|===

== clc cloud import-config

Imports the connection configuration of the given {hazelcast-cloud} cluster.

Make sure you authenticate to the {hazelcast-cloud} API using `cloud login` before running this command.

Usage:

[source,bash]
----
clc import-config [cluster-name/cluster-ID] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_CLOUD_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|
|===


== clc cloud list-custom-classes

Lists all custom classes in the {hazelcast-cloud} cluster.

Make sure you authenticate to the {hazelcast-cloud} API using `cloud login` before running this command.

Usage:

[source,bash]
----
clc cloud list-custom-classes [cluster-name/cluster-ID] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--verbose`
|Optional
|Prints additional column `Temporary Custom Classes ID`
|

|===

== clc cloud upload-custom-class

Uploads a custom class to the {hazelcast-cloud} cluster.

Make sure you authenticate to the {hazelcast-cloud} API using `cloud login` before running this command.

Usage:

[source,bash]
----
clc cloud upload-custom-class [cluster-name/cluster-ID] [file-name] [flags]
----

== clc cloud download-custom-class

Downloads a custom class from the {hazelcast-cloud} cluster.

Make sure you authenticate to the {hazelcast-cloud} API using `cloud login` before running this command.

Usage:

[source,bash]
----
clc cloud download-custom-class [cluster-name/cluster-ID] [file-name/artifact-ID] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--output-path`
|Optional
|Output path for the downloaded artifact. The base directory of the path is created recursively if it doesn’t exist.
|

|===

== clc cloud delete-custom-class

Deletes a custom class from the {hazelcast-cloud} cluster.

Make sure you authenticate to the {hazelcast-cloud} API using `cloud login` before running this command.

Usage:

[source,bash]
----
clc cloud delete-custom-class [cluster-name/cluster-ID] [file-name/artifact-ID] [flags]
----