= Installing the Hazelcast CLC
:description: The Hazelcast Command-Line Client (CLC) is available to install in macOS, Linux, and Windows environments.

// See https://docs.hazelcast.com/hazelcast/5.3-snapshot/clients/clc#installing-the-hazelcast-clc

{description} You can install the Hazelcast CLC, using one of the following:

* Using an install script on Linux or macOS
* Windows installer
* Downloading a pre-built binary

== Installing on macOS

The Hazelcast CLC is supported on macOS 15 or newer versions.

. Run the following command to install CLC using the install script we provide:
+
[source,shell,subs="attributes"]
----
curl https://hazelcast.com/clc/install.sh | bash
----

== Installing on Linux

The Hazelcast CLC runs on any recent Linux distribution. We test it on Ubuntu 22.04.

. Run the following command to install CLC using the install script we provide:
+
[source,shell,subs="attributes"]
----
curl https://hazelcast.com/clc/install.sh | bash
----

== Installing on Windows

The Hazelcast CLC is supported on Windows 10 or newer versions. We provide pre-built binaries only for 64bit Intel/AMD architecture.

. Go to the https://github.com/hazelcast/hazelcast-commandline-client/releases[releases page], and locate the Windows installer file (`hazelcast-clc-setup-v{full-version}.exe`).
. Download and the run the installer on your system to start the installation wizard.
. Follow the steps on the wizard; when you see the "Completing the Hazelcast CLC Setup Wizard" dialog, press kbd:[Finish] to complete the installation.
. `clc.exe` is automatically added to the `PATH` environment variable, so it can be started in the terminal without its full path.
. Start the Hazelcast CLC from the start menu or by running the following command.
+
[source,shell]
----
clc.exe
----

== Verifying the Hazelcast CLC Installation

To check whether the Hazelcast CLC is installed properly, run the following command on a terminal.

[source,shell]
----
clc version
----

If installed, the Hazelcast CLC version information displays.

== Uninstalling the Hazelcast CLC

Choose the option that corresponds to your installation method.

[tabs] 
==== 
Windows::
+
. Go to *Apps & Features* setting (*Start menu* -> *Windows Settings* -> *Apps*).
. Locate *Hazelcast CLC version {full-version}* under *Apps & Features* list.
. Right-click on it and select *Uninstall*.
. Press kbd:[Yes] on the uninstallation dialog.

Install Script (Linux/macOS)::
+
Delete the `$HOME/.hazelcast` directory.
====

== Next Steps

In this section you've learnt how to install the Hazelcast CLC on the supported operating systems.
To start using the Hazelcast CLC, check the following resources:

* See xref:get-started.adoc[Get Started] for a complete introduction to the Hazelcast CLC.
* See xref:configuration.adoc[Configuration] to configure the details of the connection between the Hazelcast CLC and a Hazelcast Platform cluster.
* See xref:clc-commands.adoc[Command Reference] for a complete list and descriptions of commands you can use with the Hazelcast CLC.
