= Get Started With Hazelcast Jet Job Management
:description: In this tutorial, you'll learn the basics of how to manage stream processing pipelines using the Hazelcast CLC with Hazelcast {hazelcast-cloud}. You'll see how to connect to a cluster on {hazelcast-cloud}, and submit a sample Jet job that generates a stream of numbers. You'll also learn how to use simple commands to monitor and cancel jobs.

{description}

== Before You Begin

You need the following:

- xref:install-clc.adoc[Hazelcast CLC] installed on your local machine
- One running {hazelcast-cloud} cluster. You can create a xref:managing-cloud-clusters.adoc#creating-a-cluster-on-cloud[development cluster] using the Hazelcast CLC.
- xref:cloud:ROOT:developer.adoc[{hazelcast-cloud} API key and secret]
- JRE 11 or above.
- Gradle 8 or above.

[[step-1-authenticating-with-cloud]]
== Step 1. Authenticating with {hazelcast-cloud}

To allow the Hazelcast CLC to perform cluster operations, including submitting Jet jobs, you must generate a {hazelcast-cloud} token.

. Execute the following command to retrieve the token.
+
[source,shell]
----
clc cloud login
----

. When prompted, enter your API key and secret. If both are correct, the token is retrieved and saved.

[[step-2-list-cluster-details]]
== Step 2. List Cluster Details

Next, check that the Hazelcast CLC can access your cluster by running the following command:

[source,shell]
----
clc cloud list-clusters
----

The details of all clusters linked to your {hazelcast-cloud} account are returned, including the Cluster ID, Cluster Name, Current Status, Hazelcast Version.

[[step-3-dev-configure]]
== Step 3. Connect to Your Cluster

For Hazelcast CLC to connect to your development cluster, you need to import the cluster's configuration, including its connection details.

Run the following command to save the cluster configuration with the name `dev`. Replace the `$CLUSTER_NAME` placeholder with the name of your cluster, shown in the top-left corner of the dashboard.

[source,shell]
----
clc cloud import-config $CLUSTER_NAME --name dev
----

[[step-4-build-jet-job]]
== Step 4. Build the Jet Job

Now you're ready to build the sample Jet job.

. Clone the GitHub repository.
+
[source,shell]
----
git clone https://github.com/hazelcast/hazelcast-commandline-client
----

. Switch to the project directory.
[source,shell]
----
cd hazelcast-commandline-client/examples/platform/simple-streaming-pipeline
----


. Build the project with the following command:
+

[source,shell]
----
gradle shadowJar
----

[[step-5-submit-jet-job]]
== Step 5. Submit and Monitor the Jet Job

Submitting the sample Jet job generates a stream of numbers and creates a link:https://hashids.org/[hashid] for each number. The number and hashid pair are then saved to a Map called `my-map`, with the number as the key and hashid as the value.

. Execute the following command to submit the Jet job:
+
[source,shell]
----
clc -c dev job submit build/libs/simple-streaming-pipeline-1.0-SNAPSHOT-all.jar --name simple-pipeline --wait
----
+
The Hazelcast CLC waits until the job starts to run.

. Now, list the jobs in the cluster. You should see `simple-pipeline` in a `RUNNING` state.
+
[source,shell]
----
clc -c dev job list
----

.	Create a new advanced script in your favorite text editor. For example:
+
[source,shell]
----
nano monitor.star
----

. Add the following:
+
[source,python]
----
def main():
    for i in range(1000):
        size = map_size(name="my-map")
        print(size)
        sleep(3 * SECOND)
----

. Run your script.
+
[source,shell]
----
clc -c dev script run monitor.star
----

. See how the size of `my-map` increases as entries are written to it.

. Press kbd:[Ctrl + C] when you're ready to stop the script.

[[step-6-cancel-jet-job]]
== Step 6. Cancel the Jet job

. Now, cancel the Jet job.
+
[source,shell]
----
clc -c dev job cancel simple-pipeline
----

. Run your script (from step 5) to see the size of `my-map` now.

== Summary

In this tutorial, you learned how to do the following:

* Connect to a cluster on {hazelcast-cloud}.
* Build and submit a Hazelcast Jet job to create a data pipeline.
* Manage the lifecycle of a Jet job using list and cancel commands.

== Learn More

Use these resources to continue learning:

- xref:configuration.adoc[].

- xref:clc-commands.adoc[].

- xref:clc-job.adoc[].

